[server]
port = 8888
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
cookieSecret = "3f300365abe41c0ab9367ad7e695ceda4b9f24e80986533bcff8ca56fc7f38d1"

[browser]
gatherUsageStats = false
